In [1]:
# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 배열 정렬

- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
    
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 정렬된 새로운 배열을 반환함
    
- np.argsort(arr) : 정렬 순서를 반환
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬

In [3]:
# 1차원 배열 생성
x = np.arange(0, 5)
np_print(x)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [0 1 2 3 4]
    


In [4]:
# 기존 파이썬 문법으로 순번 뒤집기
x[::-1]

array([4, 3, 2, 1, 0])

In [11]:
# 오름차순 정렬 테스트용 난수배열 만들기
# 0이상 9이하 숫자 5개를 난수생성으로 만들어서 찍어주세요.
y = np.random.randint(0,10,5)
np_print(y)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [1 5 9 4 3]
    


In [12]:
# np.sort(자료) => 원본 자료가 바뀌지는 않음
np.sort(y)

array([1, 3, 4, 5, 9])

In [13]:
y

array([1, 5, 9, 4, 3])

In [14]:
# 자료.sort() -> 원본 자료 변경
y.sort()

In [15]:
y

array([1, 3, 4, 5, 9])

In [16]:
z = np.random.randint(0, 10, 5)
np_print(z)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [6 4 7 2 8]
    


In [18]:
# np.argsort(자료)는 내부의 아이템들을 오름차순 정렬하기 위해서는
# 현재 몇 번 인덱스에 있는 자료를 어디에 배치해야 하는지 보여줌
np.argsort(z)

array([3, 1, 0, 2, 4], dtype=int64)

In [21]:
# 0이상 1미만의 범위에서 무작위로 실수값을 가지는 3행 3열의 배열 2개 생성
# np.random.random을 이용하세요.
a = np.random.random((3, 3))
b = np.random.random(9).reshape(3, 3)
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.38439383 0.23731417 0.7241529 ]
 [0.99450266 0.12845633 0.73178641]
 [0.87525148 0.26432021 0.66015755]]
    

    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.27078672 0.21022714 0.62364758]
 [0.54770045 0.09517112 0.3818331 ]
 [0.20978819 0.07468086 0.68570546]]
    


#### 예) 2차원 배열의 경우

기본값 axis = -1 <br>
현재 배열의 axis = 0, 1 <br>
마지막 axis = 1 (열별 정렬)

<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [22]:
# 기본 방향(axis=-1) => 행별 정렬
np_print(a)
np.sort(a) # axis=-1


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.38439383 0.23731417 0.7241529 ]
 [0.99450266 0.12845633 0.73178641]
 [0.87525148 0.26432021 0.66015755]]
    


array([[0.23731417, 0.38439383, 0.7241529 ],
       [0.12845633, 0.73178641, 0.99450266],
       [0.26432021, 0.66015755, 0.87525148]])

In [26]:
np_print(a)
np.sort(a, axis=1)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.38439383 0.23731417 0.7241529 ]
 [0.99450266 0.12845633 0.73178641]
 [0.87525148 0.26432021 0.66015755]]
    


array([[0.23731417, 0.38439383, 0.7241529 ],
       [0.12845633, 0.73178641, 0.99450266],
       [0.26432021, 0.66015755, 0.87525148]])

#### axis=0 (열별 정렬)

<img src='img/sortaxis0.jpg' width='200' height='200' align='left'>

In [23]:
# 열별 정렬을 시켜보세요.
np_print(a)
np.sort(a, axis=0)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.38439383 0.23731417 0.7241529 ]
 [0.99450266 0.12845633 0.73178641]
 [0.87525148 0.26432021 0.66015755]]
    


array([[0.38439383, 0.12845633, 0.66015755],
       [0.87525148, 0.23731417, 0.7241529 ],
       [0.99450266, 0.26432021, 0.73178641]])

## 인덱싱(Indexing), 슬라이싱(Slicing)

### 1. 인덱싱 : 하나의 요소에 대해 참조
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개

- 인덱싱으로 참조한 요소에 대해 수정 가능

- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [29]:
# 0 ~ 23 구간으로 1씩 증가하는 값을 아이템으로 가지는 1차원 배열을 생성해주세요.
arr1 = np.arange(0,24)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
# 1차원 배열 인덱싱 : 1차원 인덱스 요소 접근
arr1[1]

1

In [31]:
# 1차원 배열 인덱싱 : 마지막 요소 접근
arr1[-1]

23

In [32]:
# 1차원 배열 인덱싱을 통한 값 수정
arr1[-1] = 100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])