In [30]:
# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 조건 색인(Boolean Indexing)

- 배열의 요소에 대해 조건을 적용하여 True, False로 조건에 대한 결과 반환
- True에 해당하는 요소만 조회하여 조건을 만족하는 결과 반환

In [2]:
# 2차원 배열 생성
# 6 * 4로 0~ 23 만들어주세요.
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [3]:
# 스칼라연산을 이용해 10보다 큰 요소 조회하기
b > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [5]:
# 조건색인 방법
# 자료[자료를 포함한 조건식]
b[b>10]
b[b>10].size

13

In [8]:
# 조건색인을 이용해 b에서 짝수인 자료만 남겨보세요
# 조건색인에 2개 이상의 조건을 걸고 싶을때는 각 조건을 하나하나마다 ()로 감싸주고
# 조건 사이를 and인 경우는 &로, or인 경우는 |로 연결해준다.
b[(b % 2 == 0) & (b!=0)]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

### 연습문제

조건색인을 활용해 공무원시험의 합격자 평균을 구해주세요.
합격점수는 60점 이상입니다.

아래는 시험 점수 결과입니다.<br>
[31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51]

In [9]:
a = np.array([31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51])
a

array([31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51])

In [12]:
a[a >= 60].mean()

77.33333333333333

### 배열 복사

- 인덱싱, 슬라이싱을 통해 반환된 배열은 원본 배열에 대해 독립적인 새로운 객체가 아닌 원본 배열과 종속적인 객체
- 원본과 독립적인 복사본인 배열을 생성 : arr.copy() / np.copy(arr)

In [14]:
a = [1, 2, 3]
a2 = [1, 2, 3]

In [15]:
# 얕은복사
b = a

In [16]:
# 깊은복사 1:슬라이싱(전체범위 설정)을 이용한 복사
c = a2[:]

In [17]:
b[0] = 10
c[0] = 10

In [18]:
a, a2

([10, 2, 3], [1, 2, 3])

In [19]:
# 0부터 3까지 범위로 1씩 증가하는 2 x 2 구조 배열 생성
arr1 = np.arange(4).reshape(2, 2)
np_print(arr1)


    type : <class 'numpy.ndarray'>  
    shape : (2, 2)  
    dimension : 2  
    dtype : int32
    data :
 [[0 1]
 [2 3]]
    


In [20]:
# 깊은복사 2 : .copy()를 array 뒤에 붙이면 대입시 깊은복사가 일어납니다.
arr2 = arr1.copy()

In [21]:
# 얕은복사 : array도 참조형 변수여서 그냥 대입하면 얕은복사입니다.
arr3 = arr1

In [22]:
arr2[0, 0] = 100

In [23]:
arr1

array([[0, 1],
       [2, 3]])

In [24]:
arr2

array([[100,   1],
       [  2,   3]])

In [26]:
arr3[0, 0] = 100

In [27]:
arr3

array([[100,   1],
       [  2,   3]])

In [28]:
arr1

array([[100,   1],
       [  2,   3]])

### 배열 변환

#### 1. 전치(Transpose) 
- 배열의 행/열 인덱스가 바뀌는 변환
- 배열객체.T : 행/열 인덱스가 바뀐 새로운 배열을 반환하며 원본은 변경되지 않음
    
<img src='img/transpose.png' width='200' height='200' align='left'>

In [31]:
# 1이상 12이하의 값을 가지는 3 * 4 구조의 배열 생성
arr1 = np.arange(1, 13).reshape(3, 4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
# 전치행렬은 그냥 배열.T 라고 적으면 전치행렬이 됩니다.
arr1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### 2. 배열 형태 변경
- arr.ravel(), np.ravel(arr)
    - 다차원 배열을 1차원 배열로 변환
    - np.ravel() : 1차원으로 변환되는 결과는 원본 배열에 반영되지 않음
    - arr.ravel() : 1차원으로 변환하는 배열의 요소가 변경되면 원본 배열에도 반영됨
- arr.reshape(new_shape), np.reshape(arr, new_shape)
    - 원본 배열 객체의 구조(shape)를 변경
    - 변경하려는 구조의 전체 요소 개수와 원본 배열의 전체 요소 개수가 동일해야 함
    - 변경하려는 구조의 튜플 중 하나의 원소는 -1로 대체할 수 있고 다른 하나의 원소를 기준으로 계산되어 사용됨
    - reshape() 메서드가 반환하는 배열의 요소가 변경되면 원본 배열에도 반영됨

In [33]:
# 다차원 배열을 1차원 배열로 변환
arr2 = arr1.ravel()

In [34]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
# 변환 후 값 수정, 원본과 비교
arr2[0] = 10

In [37]:
arr1

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
# arr1을 6 * 2로 바꾸되 하나의 축에 대해 -1을 사용해봅시다.
arr3 = arr1.reshape(-1, 2)
arr3

array([[10,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [39]:
# 변환 후 값 수정, 원본과 비교
arr3[0] = [100, 200]

In [40]:
arr1

array([[100, 200,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

#### 3. 요소 변경, 추가, 삭제

1) 요소 변경
- arr.resize(new_shape), np.resize(arr, new_shape)
    - 배열 메서드를 사용하면 원본 변경, np 함수를 사용하면 새로운 배열 반환
    - 배열의 구조(shape)를 변경하며 원본 배열의 요소 수와 동일하지 않아도 변경 가능
    - 변경되는 배열의 요소 수가 동일할 경우 : reshape() 메서드와 동일한 결과
    - 변경되는 배열의 요소 수가 더 많을 경우 
        - np.resize(arr, new_shape) : 원본을 변경하지 않고, 모자란 부분을 기존 배열 값에서 복사해서 추가
        - arr.resize(new_shape) : 원본을 변경하고, 모자란 부분을 0으로 채움
        - 공통적으로 new_shape은 튜플로 추가
    - 변경되는 배열의 요소 수가 더 작을 경우 : 마지막 남은 요소 삭제

In [41]:
# 1이상 10미만의 범위의 랜덤 정수값으로 3 * 5 구조를 가진 배열 생성
arr = np.random.randint(1, 10, (3, 5))
arr

array([[5, 4, 8, 4, 6],
       [3, 5, 5, 3, 8],
       [7, 5, 7, 7, 5]])

In [42]:
# 1이상 10미만의 범위의 랜덤 정수값으로 3 * 5 구조를 가진 배열 생성
arr2 = np.random.randint(1, 10, (3, 5))
arr2

array([[5, 6, 4, 8, 6],
       [6, 3, 7, 8, 2],
       [3, 2, 6, 1, 6]])

In [ ]:
# 변경되는 배열의 요소 수가 같은 경우  : reshape()와 동일한 결과물

In [43]:
arr.size

15

In [44]:
arr.resize(5, 3)

In [45]:
arr

array([[5, 4, 8],
       [4, 6, 3],
       [5, 5, 3],
       [8, 7, 5],
       [7, 7, 5]])

In [ ]:
# 변경 후 배열의 요소 갯수가 더 많은 경우

In [46]:
arr3 = np.resize(arr2, (6, 3))
arr3

array([[5, 6, 4],
       [8, 6, 6],
       [3, 7, 8],
       [2, 3, 2],
       [6, 1, 6],
       [5, 6, 4]])

In [47]:
# refcheck = False인 경우만 크기가 다를때 0으로 남는 자리를 채워줌
arr.resize((6, 3), refcheck=False)
arr

array([[5, 4, 8],
       [4, 6, 3],
       [5, 5, 3],
       [8, 7, 5],
       [7, 7, 5],
       [0, 0, 0]])

In [50]:
# 변경되는 배열의 요소 수가 더 적은 경우 : 마지막 남은 요소를 삭제
# 크기가 원본과 resize를 이용했을 때 다르다면 refcheck=False를 반드시 넣는다.
arr.resize((3, 3), refcheck=False)
arr

array([[5, 4, 8],
       [4, 6, 3],
       [5, 5, 3]])

2) 요소 추가
- np.append(arr, values, axis=None)
    - arr 마지막에 values를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 결합
    - axis = 0 : 행 방향으로 결합 (단, 열의 개수가 동일해야 함)
    - axis = 1 : 열 방향으로 결합 (단, 행의 개수가 동일해야 함)
    - 원본 배열들에 반영되지 않음

In [53]:
# 1이상 10미만의 범위에서 1씩 증가하는 숫자로 3 x 3 구조의 배열 a 생성
# 10이상 19미만의 범위에서 1씩 증가하는 숫자로 3 x 3 구조의 배열 b 생성
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)
a, b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [55]:
# 2개의 배열 결합
# axis를 지정하지 않는 경우 :  np.append(arr1, arr2) => axis=None
# axis=None인 경우는 1차원으로 뭉개서 합쳐줍니다.
np.append(a, b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [56]:
# 2개의 배열 결합
# axis=0 : 행 단위 결합(행 개수가 늘어남) / 열(컬럼)개수는 3개로 유지
np.append(a, b, axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [57]:
# 2개의 배열 결합
# axis = 1 :열 방향으로 결합 / 행 개수는 동일
np.append(a, b, axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [58]:
# 열의 개수가 다른 배열(3*5)와 (3*3)을 붙여보겠습니다
c = np.arange(30, 45).reshape(3,5)
print(c)

[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


In [59]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
# 열 개수가 맞지 않으면 axis=0으로 추가 불가
np.append(c, a, axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 3

In [61]:
# 붙는 방향으로 붙여보세요.
np.append(c, a, axis=1)

array([[30, 31, 32, 33, 34,  1,  2,  3],
       [35, 36, 37, 38, 39,  4,  5,  6],
       [40, 41, 42, 43, 44,  7,  8,  9]])

In [68]:
# 어쩔 수 없이 세로로 붙이고 싶다면 3 * 5 => 5 * 3 로 변경하고 붙이면 또 세로방향으로 가능합니다.
# 전치행렬을 이용해주세요.
# 전치행렬이 어렵다면 reshape를 써서 해주세요.
np.append(c.reshape(5,3), a, axis=0)

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

- np.insert(arr, idx, values, axis=None)
    - 지정한 인덱스(idx)에 value를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열의 변형되고 해당 인덱스에 추가
    - axis = 0 : 행 방향으로 n번째 행에 추가 
    - axis = 1 : 열 방향으로 n번째 열에 추가
    - 원본 배열에 반영되지 않음

In [69]:
# 1이상 10미만 범위에서 1씩 증가하는 숫자로 3 * 3 구조의 배열을 생성해주세요.
arr = np.arange(1, 10).reshape(3, 3)
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    


In [70]:
# axis 지정하지 않는 경우 : arr를 1차원으로 변형한 후
# 변형된 배열의 지정 index에 값 추가
# 2d array를 1d array로 변형, 1번 인덱스에 100 추가
np.insert(arr, 1, 100)

array([  1, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [71]:
# 원본은 유지
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
# axis=0 : 행 방향으로 index 번재 행을 추가
# a 배열의 1번 인덱스 행에 100을 추가 => 행의 요소 개수(열 개수)만큼 100이 추가됨
np.insert(arr, 1, 100, axis=0)

array([[  1,   2,   3],
       [100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [73]:
# axis=1 : 열 방향으로 index 번째 행을 추가
# a 배열의 2번 인덱스 열에 200을 추가
np.insert(arr, 2, 200, axis=1)

array([[  1,   2, 200,   3],
       [  4,   5, 200,   6],
       [  7,   8, 200,   9]])

In [74]:
# 각 위치마다 다른 값을 주고 싶다면
# 갯수를 맞춰서 리스트로 넣어줍니다.
# arr의 2번 열에, 10, 20, 30을 각각 넣어주시면 됩니다.
np.insert(arr, 2, [10, 20, 30], axis=1)

array([[ 1,  2, 10,  3],
       [ 4,  5, 20,  6],
       [ 7,  8, 30,  9]])

3) 요소 삭제
- np.delete(arr, idx, axis=None)
    - 지정한 인덱스(idx)에 해당하는 요소를 삭제
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 해당 인덱스에 해당하는 요소를 삭제
    - axis = 0 : 행 방향으로 n번째 행을 삭제
    - axis = 1 : 열 방향으로 n번째 열을 삭제
    - 원본 배열에 반영되지 않음

In [75]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
# ravel을 이용해 1차원으로 만들어서 조회해주세요.
np.ravel(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
# axis를 지정 안 하는 경우 : 1차원 배열로 변환 -> 지정한 index에 해당하는 요소를 삭제
# a배열에 대해 1번 인덱스 요소를 삭제
np.delete(a, 1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [78]:
# 원본에는 반영이 되지 않습니다.
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
# a배열의 0번 행을 삭제(axis=0)
np.delete(a, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [80]:
# a배열의 1번 열을 삭제해주세요(axis=1)
np.delete(a, 1, axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

4) 배열 결합
- np.concatenate((arr1, arr2, ...), axis=0)
    - axis = 0(기본값) : 행 방향으로 두 배열 결합 (단, 열의 개수가 동일)
    - axis = 1 : 열 방향으로 두 배열 결합 (단, 행의 개수가 동일)
    - 원본 배열들은 변경되지 않음

In [81]:
# 1이상 7미만의 범위에서 1씩 증가하는 숫자로 2 x 3 구조의 배열 a 생성
# 7이상 13미만의 범위에서 1씩 증가하는 숫자로 2 x 3 구조의 배열 b 생성
# 13이상 23미만의 범위에서 1씩 증가하는 숫자로 2 x 5 구조의 배열 c 생성(열개수 다름)
# 23이상 38미만의 범위에서 1씩 증가하는 숫자로 5 x 3 구조읩 배열 d 생성(행개수 다름)
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
c = np.arange(13, 23).reshape(2, 5)
d = np.arange(23, 38).reshape(5, 3)

In [82]:
print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[13 14 15 16 17]
 [18 19 20 21 22]]

[[23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]



In [83]:
# axis=0(기본값): 행 방향으로 두 배열 결합
# np.append(a, b)
# [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
np.concatenate((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
# axis=1 : 열 방향으로 두 배열 결합
np.concatenate((a, b), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [85]:
# 행 방향으로 결합 :  열 개수가 동일해야함
np.concatenate((a, c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [86]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  3, 13, 14, 15, 16, 17],
       [ 4,  5,  6, 18, 19, 20, 21, 22]])

In [87]:
# 열 방향으로 결합: 행 개수 동일
# a, d를 axis=1 로 합칠경우 에러.
np.concatenate((a, d), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 5

In [88]:
np.concatenate((a, d), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])