In [1]:
# 라이브러리 불러오기
import numpy as np

In [5]:
# Numpy 객체 정보를 확인하기 위한 사용자 함수 정의 : 객체타입, 구조, 지원, 데이터타입
def np_print(arr):
    text="""
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data : \n {}""".format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

## 산술연산

- 더하기 : +, add()
- 빼기 : -, subtract()
- 나누기 : /, divide()
- 곱하기 : *, multiply()
- 지수곱 표현 : exp()
- 제곱근 : sqrt()
- 로그 : log()
- 내적(행렬곱) : dot()

In [7]:
# 1부터 10미만의 범위(지정범위)에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열의 배열
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# 4이상 13미만의 범위에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열 배열 생성
b = np.arange(4, 13).reshape(3, 3)
b

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
# 10 ~ 21까지 3행 4열 형태로 만들기
c = np.arange(10, 22).reshape(3, 4)
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### 더하기
    - 배열 + 배열
    - np.add(arr1, arr2)

In [15]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(b)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
# 산술연산자
a + b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [18]:
# np.add(배열1, 배열2)
np.add(a, b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [19]:
# 구조 다른 배열간의 산순연산자 에러 발생(+)
# 3*3 과 3*4 형태
a + c

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### 빼기
    - 배열 - 배열
    - np.subtract(arr1, arr2)

In [20]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# 산술연산자
a - b

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [22]:
b - a

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [23]:
# np.subtract(arr1, arr2)
np.subtract(a, b)

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [24]:
np.subtract(b, a)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

### 나누기
    - 배열/배열
    - np.divide(arr1, arr2)

In [25]:
# 산술연산자
a / b

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [26]:
b / a

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

In [27]:
# np.divide(arr1, arr2)
np.divide(a, b)

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [28]:
np.divide(b, a)

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

### 곱하기
    - 배열 * 배열
    - np.multiply(arr1, arr2)

In [29]:
# 산술연산자
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [30]:
b * a

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [31]:
# np.multiply(arr1, arr2)
np.multiply(a, b)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [32]:
np.multiply(b, a)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

### 지수곱 표현

- 지수(exponent) : 부동 소수점으로 숫자를 표시할 때 거듭제곱을 사용하여 표현. <br>
(예) 2.14e+2 = 2.14 x 102 = 214 / 2.98e-8 = 2.98 x 10-8 = 0.0000000298
- np.exp(arr) : 밑(base)이 자연상수 e 인 지수함수로 변환(y = e**x)

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# 지수함수
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### 제곱근

- np.sqrt(arr)

<img src='img/sqrt.gif' width='400' height='200' align='left'>

In [36]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### 내적(행렬곱)

- np.dot(a, b)

<img src='img/dotProduct.png' width='400' height='200' align='left'>

In [37]:
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [38]:
np.dot(a, b)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

### Numpy 배열 연산

#### 2. 비교 연산

1) 요소
- 값에 대한 비교 : ==, !=
- 크기에 대한 비교 : >, <, >=, <=

2) 배열
- 두 배열 전체에 대한 비교 : array_equal(a, b)

In [39]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [40]:
# 두 배열 요소에 대하여 값이 동일한지를 비교
# 반환 : 각 요소마다의 비교결과(True, False)가 배열로 표현됨
a == b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [41]:
# 두 배열 요소에 대하여 값이 다른지 비교
a != b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [42]:
# 두 배열 요소에 대해 크기 비교
a < b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [43]:
# 두 배열이 완전히 일치하는지 여부만 조회
# 하나의 T/F로 반환
np.array_equal(a, b)

False

### Numpy 배열 연산

3. 집계 함수

    - Numpy 배열에 대해 집계 함수를 적용할 때는 반드시 axis로 설정된 기준에 따라 연산 수행
    - 별도로 값을 지정하지 않으면 기본값은 axis = None으로 지정
    - axis
        - axis = None <br>
        전체 데이터를 하나의 배열로 간주하고 집계 함수의 연산 범위를 전체 배열로 지정
        <br>
        <img src='img/axis_None.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 0 <br>
        열을 기준으로 동일한 열에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_0.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 1 <br>
        행을 기준으로 동일한 행에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_1.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
    - 집계 함수 : 배열객체에 대한 메소드로 사용하거나 Numpy 라이브러리의 메소드로 사용하는 두 가지 방법
        - 합계 : sum()
        - 최소값 : min()
        - 최대값 : max()
        - 누적 합계 : cumsum()
        - 평균 : mean()
        - 중앙값 : median()
            - 크기 순으로 나열된 데이터에 대해 중앙에 위치하는 값
        - 상관계수 : corrcoef()
            - 데이터 간의 상관관계를 나타내는 수치(-1 <= r <= 1)
        - 표준편차 : std()
            - 분산의 제곱근, 데이터가 평균으로부터 흩어져 있는 정도
            - 분산 = 편차(요소-전체평균)제곱의 평균
        - 고유값 : unique()

In [44]:
# 사용할 배열 객체 확인
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
# 합계 - 전체 기준 => 모든 요소에 대한 합
# 1) 배열 타입의 메서드 : arr.sun()
# 2) numpy 함수 : np.sum(arr)
a.sum()

45

In [46]:
np.sum(a)

45

In [47]:
# 합계 - row, 가로축별 합산
# 메서드, np함수의 파라미터 값 : axis=1
# 결과값 : [0번row합, 1번row합, 2번row합...]
print(c.sum(axis=1))
print(c)

[46 62 78]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [48]:
# 합계 - column, 세로축별 합산
# 메서드, np함수의 파라미터 값 : axis=0
# 결과값 : [0번column합, 1번column합, 2번column합...]
print(c.sum(axis=0))
print(c)

[42 45 48 51]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [49]:
# 최소값 - 전체 기준
# 1) 배열 타입의 메서드 : arr.min()
# 2) numpy함수 : np.min(arr)
c.min()
np.min(c)

10

In [50]:
# (참고) 파이썬 리스트에서 최소값 찾기
x = [1, 2, 3, 4]
min(x)

1

In [55]:
# 최소값 - 각 가로축(row)별 최소값 찾기
# 결과값 : [0번째 row최소값, 1번쨰 row최소값...]
print(c.min(axis=1))
print(c)
np.min(c, axis=1)

[10 14 18]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([10, 14, 18])

In [56]:
# 최소값 - 각 세로축(coiumn)별 최소값 찾기
# 결과값 : [0번째 coiumn최소값, 1번쨰 coiumn최소값...]
print(c.min(axis=0))
print(c)
np.min(c, axis=0)

[10 11 12 13]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([10, 11, 12, 13])